#!/bin/bash
help()
{
    # Display Help
    echo "Configure MCTP interfaces and discover MCTP end points."
    echo
    echo "Usage: $0 [-c][-d][-h][-u]"
    echo "Options:"
    echo "-c Delete the MCTP configuration"
    echo "-d Trigger the MCTP discovery process"
    echo "-h Display this help message"
    echo "-u Bring up the MCTP interfaces"
    echo
}

MCTP_NETWORK_ID=1
MCTP_LOCAL_ENDPOINT_ID=8

#get the root i2c bus number if the mctp i2c interfaces are behind a switch
ROOT_I2C_NUM=
mctp_i2c_root_intf_get()
{
    shopt -s extglob
    for F in /sys/bus/i2c/devices/i2c-*/of_node/mctp@10
    do
        if test -d "$F"; then
            ROOT_I2C_NUM=$(echo "$F"|cut -d'-' -f 2 | cut -d'/' -f 1)
        fi
    done
}

mctp_local_endpoint_id_set()
{
    local OP=$1
    local MCTP_INTF=$2
    local ENDPOINT_ID=$3

    if ! mctp addr "${OP}" "${ENDPOINT_ID}" dev "${MCTP_INTF}" 2>&1 |
            logger -t amd-mctp-config; then
        #log the error and continue configuring
        logger -t amd-mctp-config \
            "mctp addr ${OP} ${ENDPOINT_ID} dev ${MCTP_INTF} failed."
    fi
}

mctp_intf_config()
{

    # Use mapfile to read the contents of /sys/class/net and filter interfaces using awk
    # $0 - interface name
    #  ~ - pattern matching operator in awk
    # shellcheck disable=SC2012
    mapfile -t MCTP_INTF_LIST < <(ls /sys/class/net | awk -v pattern="mctp$1" '$0 ~ pattern {print $0}')
    local LINK_STATE="$2"

    if [ "${#MCTP_INTF_LIST[@]}" -eq 0 ]; then
        logger -t amd-mctp-config \
            "No MCTP $1 interfaces are configured on the system."
        return
    fi

    if [ "$1" == "i2c" ]; then
	unset "MCTP_INTF_LIST[-1]"
    fi

    for MCTP_INTF in "${MCTP_INTF_LIST[@]}"
    do
        #set the interface state
        if ! mctp link set "${MCTP_INTF}" "$LINK_STATE" net "${MCTP_NETWORK_ID}" 2>&1 |
                logger -t amd-mctp-config; then
            #log the error and continue bring up the next interface
            logger -t amd-mctp-config \
                "mctp link set ${MCTP_INTF} ${LINK_STATE} net ${MCTP_NETWORK_ID} failed."
        else
            if [ "$LINK_STATE" == "up" ]; then
                #add local endpoint to the interface
                mctp_local_endpoint_id_set "add" "${MCTP_INTF}" "${MCTP_LOCAL_ENDPOINT_ID}"
            else
                #delete local endpoint to the interface
                mctp_local_endpoint_id_set "del" "${MCTP_INTF}" "${MCTP_LOCAL_ENDPOINT_ID}"
            fi
            MCTP_LOCAL_ENDPOINT_ID=$((MCTP_LOCAL_ENDPOINT_ID + 1))
        fi
    done
}

mctp_i2c_discover()
{
    #prepare list of mctp i2c interfaces
    # shellcheck disable=SC2012
    mapfile -t MCTP_I2C_INTF_LIST < <(ls /sys/class/net | awk -v pattern=mctpi2c '$0 ~ pattern {print $0}')
    if [ "${#MCTP_I2C_INTF_LIST[@]}" -eq 0 ]; then
        logger -t amd-mctp-config \
            "No MCTP I2C interfaces are configured on the system."
        return
    fi

    # do the i2c MCTP endpoint discovery for each interface
    mctp_i2c_root_intf_get
    for MCTP_I2C_INTF in "${MCTP_I2C_INTF_LIST[@]}"
    do
        #skip the discovery for the root bus number
        if [ mctpi2c"${ROOT_I2C_NUM}" == "${MCTP_I2C_INTF}" ]; then
            continue
        fi

        logger -t amd-mctp-config \
            "Discovering MCTP endpoints on the $MCTP_I2C_INTF..."

        # prepare a list of i2c devices that are seen on the bus and are not
        # associated with any driver and issue the endpoint assignment command
        # to them.
        I2C_BUS_NUM=${MCTP_I2C_INTF//mctpi2c/}
        I2C_ADDRS=$(i2cdetect -y "${I2C_BUS_NUM}" | cut -d':' -f 2 |
                    grep -v "    0"|tr -dc '[0-9][a-f] ')
        for I2C_ADDR in $I2C_ADDRS
        #for (( I2C_ADDR=8; I2C_ADDR<119; I2C_ADDR++ ))
        do
            busctl call au.com.codeconstruct.MCTP1 \
                /au/com/codeconstruct/mctp1/interfaces/"${MCTP_I2C_INTF}" \
                au.com.codeconstruct.MCTP.BusOwner1 AssignEndpoint \
		ay 1 0x"${I2C_ADDR}" 2>&1 |
                    logger -t amd-mctp-config
                logger -t amd-mctp-config "for 0x${I2C_ADDR}"
        done
        logger -t amd-mctp-config \
            "Discovering MCTP endpoints on the $MCTP_I2C_INTF... Done."

        # configure the local endpoint id for this interface if needed.
        # On all the AMD boards, all the PCIe slots are behind a switch and the
        # local endpoint id is configured for the root bus as part of
        # mctpi2c interface configuration.
    done

    #add the mctp route and neighbor informaiton to journalctl.
    logger -t amd-mctp-config "mctp route show:"
    mctp route show 2>&1 | logger -t amd-mctp-config
    logger -t amd-mctp-config ""
    logger -t amd-mctp-config "mctp neighbor show:"
    mctp neigh show | logger -t amd-mctp-config
    logger -t amd-mctp-config ""
    logger -t amd-mctp-config "busctl tree au.com.codeconstruct.MCTP1:"
    busctl tree au.com.codeconstruct.MCTP1 | logger -t amd-mctp-config
}

# print help if no arguments are given
if [ $# -eq 0 ]; then
    help
    exit 1
fi

while getopts ":cdhu" OPTION; do
    case $OPTION in
	c) #cleanup the mctp configuration
            mctp_intf_config "pcie" "down"
            mctp_intf_config "i3c" "down"
            mctp_intf_config "i2c" "down"
            ;;

        d) # trigger the discovery process
            mctp_i2c_discover "$MCTP_I2C_NETWORK_ID"
            ;;

        h) # display Help
            help
            exit 0;;

        u) # type of interface
            mctp_intf_config "pcie" "up"
            mctp_intf_config "i3c" "up"
            mctp_intf_config "i2c" "up"

            # add the following log informaiton to journalctl
            # will be helpful for system debug
            mctp link show 2>&1 | logger -t amd-mctp-config
            ;;

        *) # display Help
            help
            exit 0;;
    esac
done
exit $?
