# Overwrite flash layout
FLASH_SIZE = "131072"
FLASH_BMCU_SIZE:flash-131072 = "768"
FLASH_BMCU_OFFSET:flash-131072 = "0"
FLASH_UBOOT_OFFSET:flash-131072 = "768"
FLASH_UBOOT_ENV_OFFSET:flash-131072 = "2048"
FLASH_KERNEL_OFFSET:flash-131072 = "2176"
FLASH_ROFS_OFFSET:flash-131072 = "18560"
FLASH_RWFS_OFFSET:flash-131072 = "98304"
RWFS_SIZE = "33554432"

# Kernel Build Settings
KMACHINE = "aspeed"
KERNEL_DEVICETREE = "aspeed/${KMACHINE}-bmc-amd-congo.dtb \
                     aspeed/${KMACHINE}-bmc-amd-ghana.dtb \
                     aspeed/${KMACHINE}-bmc-amd-kenya.dtb \
                     aspeed/${KMACHINE}-bmc-amd-marley.dtb \
                     aspeed/${KMACHINE}-bmc-amd-morocco.dtb \
                     aspeed/${KMACHINE}-bmc-amd-nigeria.dtb \
                    "

# U-Boot Build Settings
UBOOT_MACHINE = "ast2700_sp7_defconfig"
UBOOT_DEVICETREE = "ast2700-sp7"
UBOOT_SIGN_ENABLE = "0"
UBOOT_FITIMAGE_ENABLE = "1"

# BootMCU Build Settings
BOOTMCU_MACHINE = "ibex-ast2700_defconfig"
BOOTMCU_FW_BINARY = "ast2700-ibex-spl.bin"

require conf/machine/include/ast2700-sdk.inc
require conf/machine/include/ast-optee-os.inc
require conf/machine/include/obmc-bsp-common.inc
require conf/machine/include/amd-withhost.inc
require conf/distro/include/pldm.inc

#TODO Enable once back-end support available
IMAGE_FEATURES:remove:sp7 = " \
        obmc-leds \
        obmc-fan-control \
        obmc-fan-mgmt \
"

# TODO: Enable these recipe's once the sp7 machine specific
#       support is available.
BMASK += "recipes-amd/amd-fpga/amd-fpga.bb"

#TODO Remove once apml inband driver support is available in the kernel
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"
KERNEL_MODULE_AUTOLOAD += "apml_sbtsi apml_sbrmi"

SERIAL_CONSOLES = "115200;ttyS12"

OVERRIDES .= ":amd"
