#!/bin/bash

# Multi Host Service, object, and interface to monitor
readonly SERVICE="xyz.openbmc_project.Settings"
readonly OBJECT="/xyz/openbmc_project/control/HostMode"
readonly INTERFACE="xyz.openbmc_project.Control.HostMode"
readonly CURRENT_MODE="CurrentMode"
readonly USER_MODE="Mode"

# Platform config GPIOs

# Read the GPIO base value
GPIOCHIP=$(cat /sys/devices/platform/soc@14000000/14c34c00.ltpi0-gpio/gpio/*/base)
readonly GPIOCHIP
readonly MGMT_MON_PLATFORM_CONFIG=$((GPIOCHIP + 102))
readonly MGMT_ASSERT_PLATFORM_CONFIG=$((GPIOCHIP + 103))

# Directory for AMD configuration files
readonly CONFIG_DIR="/etc/amd"

# Directory for host-specific configurations
readonly HOST_CONFIG_DIR="$CONFIG_DIR/hosts.d"

# Directory for runtime data
readonly MULTI_HOST_CONFIG_DIR="/var/lib/multi-host-config"
readonly MULTI_HOST_CURRENT_MODE_FILE="current-mode"

# Host names
readonly CONF_SINGLE_HOST="host0.conf"
readonly CONF_HOST1="host1.conf"
readonly CONF_HOST2="host2.conf"

# d-bus Constants
readonly BASE_CHASSIS_PATH="/xyz/openbmc_project/state/chassis"
readonly CHASSIS_PATH_0="${BASE_CHASSIS_PATH}0"
readonly CHASSIS_PATH_1="${BASE_CHASSIS_PATH}1"
readonly CHASSIS_PATH_2="${BASE_CHASSIS_PATH}2"
readonly TRANSITION_OFF="xyz.openbmc_project.State.Chassis.Transition.Off"
readonly CHASSIS_INTERFACE="xyz.openbmc_project.State.Chassis"

readonly CHASSIS_SERVICE_0="${CHASSIS_INTERFACE}0"
readonly CHASSIS_SERVICE_1="${CHASSIS_INTERFACE}1"
readonly CHASSIS_SERVICE_2="${CHASSIS_INTERFACE}2"

# HPM board ID
HPM_BOARD_ID=0

# Function to set the MGMT_PLATFORM_CONFIG GPIO pins
set_platform_gpio_pin() {
    GPIO=$1
    value=$2

    if [ ! -d "/sys/class/gpio/gpio$GPIO" ]; then
        echo "$GPIO" >/sys/class/gpio/export
        cd "/sys/class/gpio/gpio$GPIO" || exit 1
    else
        cd "/sys/class/gpio/gpio$GPIO" || exit 1
    fi
    echo "$value" > value
    echo "$GPIO" > /sys/class/gpio/unexport

    return 0
}

# Function to get the MGMT_PLATFORM_CONFIG GPIO pins
get_platform_gpio_pin() {
    GPIO=$1

    if [ ! -d "/sys/class/gpio/gpio$GPIO" ]; then
        echo "$GPIO" > /sys/class/gpio/export
    fi

    GPIO_PATH="/sys/class/gpio/gpio$GPIO"

    if [ ! -d "$GPIO_PATH" ]; then
        echo "Error: GPIO $GPIO not found" >&2
        return 1
    fi

    gpio_val=$(cat "$GPIO_PATH/value")
    echo "$GPIO" > /sys/class/gpio/unexport
    echo "$gpio_val"

    return 0
}

# Function to perform custom multi-host power off action
power_off() {
    local mode=$1

    # Power off host based on processor mode
    if [ "$mode" -eq 0 ]; then
        busctl set-property "$CHASSIS_SERVICE_0" "$CHASSIS_PATH_0" "$CHASSIS_INTERFACE" RequestedPowerTransition s "$TRANSITION_OFF"
    elif [ "$mode" -eq 1 ]; then
        busctl set-property "$CHASSIS_SERVICE_1" "$CHASSIS_PATH_1" "$CHASSIS_INTERFACE" RequestedPowerTransition s "$TRANSITION_OFF"
        busctl set-property "$CHASSIS_SERVICE_2" "$CHASSIS_PATH_2" "$CHASSIS_INTERFACE" RequestedPowerTransition s "$TRANSITION_OFF"
    fi
}

# Function to configure the BRD_ID FRU for P0 and P1 based on the current mode
# configured by the user.
configure_board_id_fru() {
    local p0_bus=12
    local p1_bus=13
    local brd_id_slave=0x53
    local brd_id_mux=0x70
    local brd_id_channel=0x01
    local mode=$1

    echo "DEBUG: Programming BRD_ID FRU for mode $mode"
    #Set the Board ID FRU base on the mode and platform
    if [[ $mode == 1 ]]; then
        if [[ "$HPM_BOARD_ID" == "87" ]]; then #Morocco Validation
            P0_board_id=8F
            P1_board_id=90
        elif [[ "$HPM_BOARD_ID" == "82" ]]; then #Morocco major performance
            P0_board_id=9A
            P1_board_id=9B
        elif [[ "$HPM_BOARD_ID" == "83" ]]; then #Morocco minor performance
            P0_board_id=9C
            P1_board_id=9D
        elif [[ "$HPM_BOARD_ID" == "85" ]]; then #Nigeria
            P0_board_id=91
            P1_board_id=92
        elif [[ "$HPM_BOARD_ID" == "8E" ]]; then #Ghana
            P0_board_id=93
            P1_board_id=94
        fi
    elif [[ $mode == 0 ]]; then
        if [[ "$HPM_BOARD_ID" == "87" ]]; then #Morocco Validation
            P0_board_id=87
            P1_board_id=90
        elif [[ "$HPM_BOARD_ID" == "82" ]]; then #Morocco major performance
            P0_board_id=82
            P1_board_id=9B
        elif [[ "$HPM_BOARD_ID" == "83" ]]; then #Morocco minor performance
            P0_board_id=83
            P1_board_id=9D
        elif [[ "$HPM_BOARD_ID" == "85" ]]; then #Nigeria
            P0_board_id=85
            P1_board_id=92
        elif [[ "$HPM_BOARD_ID" == "8E" ]]; then #Ghana
            P0_board_id=8E
            P1_board_id=94
        fi
    fi

    #Set mux setttings to acces brd_id
    i2cset -y -f $p0_bus $brd_id_mux $brd_id_channel
    i2cset -y -f $p1_bus $brd_id_mux $brd_id_channel

    #Set Board ID field at offset 16 (0x10)
    if [[ $mode == 0 ]]; then
        i2ctransfer -f -y $p0_bus w3@$brd_id_slave 0x00 0x10 0x0$P0_board_id
        i2ctransfer -f -y $p1_bus w3@$brd_id_slave 0x00 0x10 0x0$P1_board_id

    elif [[ $mode == 1 ]]; then
        i2ctransfer -f -y $p0_bus w3@$brd_id_slave 0x00 0x10 0x0$P0_board_id
        i2ctransfer -f -y $p1_bus w3@$brd_id_slave 0x00 0x10 0x0$P1_board_id
    fi
}

# Function to monitor multi-host state changes via D-Bus property
monitor_multi_host_state_change() {
    dbus-monitor --system "type='signal',\
        interface='org.freedesktop.DBus.Properties',\
        member='PropertiesChanged',\
        path='$OBJECT',\
        arg0namespace='$INTERFACE'" | while read -r line; do
        if echo "$line" | grep -q "string \"Mode\""; then
            user_config_mode=$(busctl get-property $SERVICE $OBJECT $INTERFACE $USER_MODE | awk '{print $2}')
            current_mode=$(cat "$MULTI_HOST_CONFIG_DIR/$MULTI_HOST_CURRENT_MODE_FILE")
            # Check if the mode configured by user is same as the current mode
            if [[ $user_config_mode != $current_mode ]]; then
                echo "Host mode changed"

                setMode $user_config_mode
                if [ $? == 1 ]; then
                    echo "Host mode configured: $user_config_mode"
                    reboot
                fi
            else
                echo "No Mode change detected..continue monitoring!!"
            fi
        fi
        done
}

# Function to configure the boot mode
setMode() {
    local mode="$1"
    local bootstrap_mode

    if [[ "$mode" == 0 ]]; then
        # Create host0 file
        touch "$HOST_CONFIG_DIR/$CONF_SINGLE_HOST"

        # Remove host1 and host2 file
        rm -rf $HOST_CONFIG_DIR/$CONF_HOST1
        rm -rf $HOST_CONFIG_DIR/$CONF_HOST2

        # Check the bootstrap mode
        bootstrap_mode=$(get_platform_gpio_pin "$MGMT_MON_PLATFORM_CONFIG")

        echo "DEBUG: bootstrap_mode $bootstrap_mode "
        if [[ "$bootstrap_mode" != 0 ]]; then
            # Power off host0
            power_off "$bootstrap_mode"

            # Configure BRD_ID_EEPROM
            configure_board_id_fru "$mode"

            # Set the bootstrap mode
            set_platform_gpio_pin "$MGMT_ASSERT_PLATFORM_CONFIG" "$mode"
        fi

        # Set the new current mode
        busctl set-property $SERVICE $OBJECT $INTERFACE $CURRENT_MODE q $mode
        echo $mode > $MULTI_HOST_CONFIG_DIR/$MULTI_HOST_CURRENT_MODE_FILE
        return 1
    elif [[ "$mode" == 1 ]]; then
        # Create host1 and host2 files
        touch $HOST_CONFIG_DIR/$CONF_HOST1
        touch $HOST_CONFIG_DIR/$CONF_HOST2

        # Remove host0 config if present
        rm -rf $HOST_CONFIG_DIR/$CONF_SINGLE_HOST

        # Check the bootstrap mode
        bootstrap_mode=$(get_platform_gpio_pin "$MGMT_MON_PLATFORM_CONFIG")

        if [[ "$bootstrap_mode" != 1 ]]; then
            # Power off host1 and host2
            power_off "$bootstrap_mode"

            # Configure BRD_ID_EEPROM
            configure_board_id_fru "$mode"

            # Set the bootstrap mode
            set_platform_gpio_pin "$MGMT_ASSERT_PLATFORM_CONFIG" "$mode"
        fi

        # Set the new current mode
        busctl set-property $SERVICE $OBJECT $INTERFACE $CURRENT_MODE q $mode
        echo $mode > $MULTI_HOST_CONFIG_DIR/$MULTI_HOST_CURRENT_MODE_FILE
        return 1
    else
        echo "Invalid mode: $mode"
        return 0
    fi
}

# Main function
main() {
    # Create the directory if it doesn't exist
    mkdir -p "$CONFIG_DIR"
    mkdir -p "$MULTI_HOST_CONFIG_DIR"
    mkdir -p "$HOST_CONFIG_DIR"

    HPM_BOARD_ID=$(/sbin/fw_printenv -n board_id)
    echo "INFO: HPM Board ID - $HPM_BOARD_ID"

    # Check for 2P Platforms Morocco(0x82, 0x83, 0x87), Nigeria(0x85), Ghana(0x8E)
    if [[ ! "$HPM_BOARD_ID" =~ ^(82|83|85|87|8E)$ ]]; then
        echo "INFO: Single Host supported System"
        # Setup default hosts configurations
        touch "$HOST_CONFIG_DIR/$CONF_SINGLE_HOST"

        echo "multi-host-config: Configuration setup completed successfully."
        exit 0
    fi

    if [ ! -e $MULTI_HOST_CONFIG_DIR/$MULTI_HOST_CURRENT_MODE_FILE ]; then
        echo "First time boot or factory reset"

        current_mode=0
        touch $MULTI_HOST_CONFIG_DIR/$MULTI_HOST_CURRENT_MODE_FILE
        echo 0 > $MULTI_HOST_CONFIG_DIR/$MULTI_HOST_CURRENT_MODE_FILE

    else
        current_mode=$(cat "$MULTI_HOST_CONFIG_DIR/$MULTI_HOST_CURRENT_MODE_FILE")
    fi

    # Configure the curent mode
    echo "DEBUG: Setting current mode $current_mode"
    setMode $current_mode

    # Monitor the D-Bus property change
    echo "DEBUG: Monitoring D-Bus"
    monitor_multi_host_state_change

    if [ $? == 1 ]; then
        reboot;
    fi

    echo "Multi-host configuration failed"
}

# Call the main function
main
