#!/bin/bash

set +e
exec 2> /dev/null # remove on debug

I2CBUS=12
FPGAADDR=0x50

function read_reg()
{
    local FPGA_REG=$1
    local DATA=$(i2cget -y $I2CBUS $FPGAADDR $(printf "0x%x" $FPGA_REG))
    echo -ne $((DATA))
}
function get_board_info ()
{
    local name
    # Read Board ID from u-boot env
    boardID=$(read_reg 1)
    case $boardID in
    "128" | "129" | "134")
        name="Congo"
        ;;
    "130" | "131" | "135")
        name="Morocco"
        ;;
    "132")
        name="Kenya"
        ;;
    "133")
        name="Nigeria"
        ;;
    "142")
        name="Ghana"
        ;;
    *)
        name="SP7"
        ;;
    esac
    if [ "$1" == "name" ]; then
        echo -ne $name
    fi
    if [ "$1" == "rev" ]; then
        revID=`fw_printenv |grep -i board_rev |cut  -c 11-12`
        echo -ne $revID
    fi
    if [ "$1" == "id" ]; then
        echo -ne $boardID
    fi
    echo " "
}

function get_hpm_fpga_ver()
{
    declare -A revision_map=( [82]="R" [84]="T" )
    temp=$(read_reg 2)
    REV_W=${revision_map[$temp]:-?}
    REV_X=$(read_reg 3)
    REV_Y=$(read_reg 4)
    REV_Z=$(read_reg 5)
    echo -ne $REV_W$REV_X.$REV_Y.$REV_Z
}
# all arguments are function names. invoke directly
if [ ! -z "$1" ] ; then
    $@
fi
